import streamlit as st
import yfinance as yf
from google.genai import types
import plotly.graph_objects as go
import pandas as pd
from fpdf import FPDF
import requests

# --- CONFIGURATION ---
st.set_page_config(page_title="AI Stock Agent 2026", layout="wide", page_icon="📈")

# Accessing Gemini API
    API_KEY = st.secrets["GOOGLE_API_KEY"]
    client = genai.Client(api_key=API_KEY)

# --- HELPER FUNCTIONS ---

def get_ticker_and_info(query):
    """Resolves name to ticker and fetches company metadata"""
    try:
        search_url = f"https://query2.finance.yahoo.com/v1/finance/search?q={query}"
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(search_url, headers=headers).json()
        ticker = response['quotes'][0]['symbol']
        
        # Get metadata for logo discovery
        stock_info = yf.Ticker(ticker).info
        website = stock_info.get('website', '').replace('http://', '').replace('https://', '').split('/')[0]
        name = stock_info.get('longName', ticker)
        
        return ticker, name, website
    except:
        return None, None, None

def generate_pdf(ticker, name, analysis):
    """Creates a downloadable PDF report"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 15, f"Equity Research Report: {name} ({ticker})", ln=True, align="C")
    pdf.ln(10)
    pdf.set_font("Arial", size=11)
    # multi_cell is critical for wrapping AI text
    pdf.multi_cell(0, 8, analysis)
    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 10, "Generated by AI Stock Agent - For Educational Purposes Only", align="C")
    return pdf.output()

# --- MAIN UI ---
st.title("🤖 Autonomous AI Stock Intelligence")
st.markdown("---")

# Sidebar Search
st.sidebar.header("Search Engine")
user_query = st.sidebar.text_input("Enter Company Name (e.g., Apple, Microsoft)", value="NVIDIA")
run_analysis = st.sidebar.button("Run Comprehensive Analysis")

if run_analysis:
    ticker, comp_name, domain = get_ticker_and_info(user_query)
    
    if not ticker:
        st.error("Could not resolve company name. Please try the exact Ticker symbol.")
    else:
        # Display Header with Logo
        header_col1, header_col2 = st.columns([1, 6])
        with header_col1:
            if domain:
                logo_url = f"https://logo.clearbit.com/{domain}"
                st.image(logo_url, width=80)
        with header_col2:
            st.subheader(f"{comp_name} ({ticker})")
            st.caption(f"Domain: {domain}")

        # Data Fetching
        with st.spinner("Fetching market data..."):
            stock = yf.Ticker(ticker)
            hist = stock.history(period="3mo")

        with st.spinner("Agent is reasoning..."):
            try:
                # 1. Clean the prompt to ensure no empty/weird characters
                clean_prompt = str(prompt).strip()
        
                if not clean_prompt:
                    st.error("The prompt was empty. Please check your ticker and data.")
                    st.stop()

                # 2. Use the new 2026 method structure with explicit contents
                # We wrap the string in a list to satisfy the SDK's internal validation
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=[clean_prompt] 
                )

                # 3. Validation check before accessing .text
                if response and hasattr(response, 'text'):
                    analysis_text = response.text
                    st.info(analysis_text)
                else:
                    st.error("The AI returned an empty response. Please try again.")
                    
            except Exception as ai_e:
                # This will catch the specific API/Network error you're seeing
                st.error(f"AI Reasoning Error: {ai_e}")
                st.write("Troubleshooting: Check your internet connection and verify your API key is active.")

        if hist.empty:
            st.warning("Data unavailable for this ticker.")
        else:
            # Layout
            col_chart, col_ai = st.columns([2, 1])
            
            with col_chart:
                fig = go.Figure(data=[go.Candlestick(x=hist.index, open=hist['Open'], 
                                                     high=hist['High'], low=hist['Low'], 
                                                     close=hist['Close'], name="OHLC")])
                fig.update_layout(title="3-Month Price Action", template="plotly_dark", height=500)
                st.plotly_chart(fig, use_container_width=True)

            with col_ai:
                st.write("### 🧠 AI Analyst Perspective")
                data_tail = hist.tail(5).to_string()
                
                # Dynamic Prompting
                prompt = f"""Conduct a senior-level analysis for {comp_name} ({ticker}).
                Current Data: {data_tail}.
                Provide:
                1. Market Trend Analysis
                2. Final Recommendation (BUY/SELL/HOLD)
                3. Risk/Reward Rating."""

                with st.spinner("Agent is reasoning..."):
                    ai_response = client.models.generate_content(model="gemini-2.0-flash", contents=prompt)
                    analysis_text = ai_response.text
                    st.info(analysis_text)
                
                # PDF BUTTON: Now dynamically visible after analysis is ready
                st.markdown("---")
                pdf_data = generate_pdf(ticker, comp_name, analysis_text)
                st.download_button(
                    label="📥 Download Research PDF",
                    data=bytes(pdf_data),
                    file_name=f"{ticker}_Report.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )

# Footer
st.sidebar.markdown("---")
st.sidebar.info("v2.1 Update: Integrated Clearbit Logo API & Gemini 2.0 Unified SDK.")
